TRUNCATE TABLE utente;
TRUNCATE TABLE serie;

SET FOREIGN_KEY_CHECKS=0;


-- utente

-- INSERT INTO Utente VALUES(id, user, pass, mail, img, nome, cognome, dataNasc, tipo);
INSERT INTO utente VALUES ('1', 'admin', 'admin', 'admin@support.it', '', 'Lorenzo', 'Busin', '1997/05/16', 'admin');
INSERT INTO utente VALUES ('2', 'user', 'user', 'abrook@live.it', '', 'Alyce', 'Brook', '1993/04/30', 'user');
INSERT INTO utente VALUES ('3', 'user1', 'user1', 'cornish3@google.com.br' , '', 'Annamaria', 'Cornish', '1988/02/21', 'user');
INSERT INTO utente VALUES ('4', 'user2', 'user2', 'cchinghnam@yahoo.com', '', 'Cyndi', 'Highnam', '1997/01/08', 'user');
INSERT INTO utente VALUES ('5', 'user3', 'user3', 'johnslo@gmail.com', '', 'John', 'Slowan', '1994/09/06', 'user');

-- serie

-- INSERT INTO serie VALUES(id, img, titolo, distr, desc, creatore, flag_terminata, consigliato, non_cons, pref, voto);
INSERT INTO serie VALUES('1', '', 'Narcos', 'Netflix', 'La serie racconta la storia vera della dilagante diffusione della cocaina tra Stati Uniti ed Europa negli anni ottanta. Le prime due stagioni sono incentrate sulla lotta delle autorità colombiane e della DEA contro il narcotrafficante Pablo Escobar e il cartello di Medellín, mentre la terza stagione è incentrata sulla lotta al cartello di Cali, guidato dai fratelli Gilberto e Miguel Rodríguez Orejuela.', 'Chris Brancato', '1', '0', '0', '0', '0' );
INSERT INTO serie VALUES('2', '', 'Daredevil', 'Netflix', 'Matt Murdock, dopo aver perso la vista da bambino a causa di un incidente radioattivo, sviluppa dei sensi sovrumani e li utilizza per combattere il crimine per le strade della sua città nei panni del supereroe Daredevil. Nella prima stagione Matt affronta il potente signore del crimine Wilson Fisk, alias Kingpin, impegnato nella sua opera di riqualificazione del quartiere in combutta con vari esponenti della malavita della città.Nella seconda stagione Matt continua a cercare di gestire la sua doppia vita come avvocato e supereroe; il suo cammino lo porta ad incrociarsi con il freddo, violento e spietato vigilante Frank Castle, alias The Punisher,e con la sua vecchia fiamma Elektra, assieme alla quale affronta una antica e potente setta ninja, la Mano.', 'Drew Goddard', '0', '0', '0', '0', '0' );
INSERT INTO serie VALUES('3', '', 'The Walking Dead', 'AMC', 'Rick Graims è un vice sceriffo vittima di un incidente durante uno scontro a fuoco con dei fuorilegge: colpito alla schiena, va in coma, lasciando tra le lacrime la moglie Lori e il figlio Carl. Il risveglio, poco tempo dopo, è traumatico. Rick non ci metterà molto a capire la situazione: il virus che sembrava essere controllato prima del suo incidente, ha preso piede.', 'Frank Darabont', '0', '0', '0', '0', '0' );
INSERT INTO serie VALUES('4', '', 'Hill House', 'Netflix', 'La serie racconta la storia di un gruppo di fratelli che, da bambini, sono cresciuti in quella che in seguito sarebbe diventata la casa infestata più famosa del paese. Ora adulti e costretti a stare di nuovo insieme di fronte alla tragedia, la famiglia deve finalmente affrontare i fantasmi del loro passato, alcuni dei quali sono ancora in agguato nelle loro menti.', 'Mike Flanagan', '0', '0', '0', '0', '0' );
INSERT INTO serie VALUES('5', '', 'Gomorra', 'Sky', 'Liberamente ispirata al best seller di Roberto Saviano, la serie racconta le gesta di camorristi, spacciatori di droga, che agiscono nella periferia di Napoli. Nel contesto di organizzazioni criminali di stampo mafioso, con ramificazioni nel mondo degli affari e in quello della politica, i personaggi sono descritti con crudo realismo e presentano un complesso miscuglio di comportamenti talvolta brutali e avidi, talaltra pseudo sentimentali.', 'Roberto Saviano', '0', '0', '0', '0', '0' );
INSERT INTO serie VALUES('6', '', 'Breking Bad', 'AMC', 'Quando a Walter viene diagnosticato un cancro ai polmoni, i suoi problemi sembrano precipitare. Tuttavia, in seguito al casuale incontro con Jesse Pinkman, un suo ex studente diventato uno spacciatore di poco conto, Walter decide di cucinare i cristalli di metanfetamina. Il prodotto di Walter si rivela però di qualità nettamente superiore rispetto alla concorrenza, con una purezza del 99,1%, derivante dalle sue conoscenze chimiche. Decide quindi di sfruttare le sue capacità per prendere il controllo del mercato della droga.', 'Vince Gilligan', '1', '0', '0', '0', '0' );
INSERT INTO serie VALUES('7', '', 'Mr Robot', 'UCB', 'Elliot viene avvicinato da Mr. Robot, un misterioso anarchico-insurrezionalista, che intende introdurlo in un gruppo di hacktivisti conosciuti con il nome di fsociety. Il manifesto di fsociety è liberare la popolazione dai debiti con le banche e smascherare i potenti che stanno distruggendo il mondo.', 'Sam Esmail', '0', '0', '0', '0', '0' );
INSERT INTO serie VALUES('8', '', 'Sherlock', 'BBC', 'La serie è un libero adattamento dei romanzi e dei racconti di Sir Arthur Conan Doyle e vede come protagonista il detective Sherlock Holmes, affiancato dal suo amico e assistente, il dottor John Watson. Le avventure dei due si svolgono però nella Londra odierna, e non in quella presentata da Doyle. Watson è un reduce della guerra in Afghanistan e deve ancora ritrovare il suo posto nella società. Quando un amico gli suggerisce di trovarsi un coinquilino con cui dividere le spese di un appartamento, si ritrova a vivere con Sherlock Holmes, che col passare degli anni diventerà suo compagno di vita.', 'Steven Moffat', '0', '0', '0', '0', '0' );